name: Example Workflow
on: push
env:
   GLOBAL_VAR: "Hello"
jobs:
  test:
     runs-on: ubuntu-latest
     env:
       JOB_VAR: "World"
     steps:
      - name: Print variables
        run: |
          echo $GLOBAL_VAR
          echo $JOB_VAR
          echo $username
  deploy:
    runs-on: ubuntu-latest
    env:
      username: "Muhammad"
    steps:
      - name: display vars values
        run: |
          echo $GLOBAL_VAR
          echo $username
          echo $JOB_VAR
          echo "Repo is ${{ github.repository }}"
          echo " secret for username in Dockerhub is ${{ secrets.DOCKERHUB_USERNAME }}
      
      
